@url=http://localhost:3333
@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4Y2UyMTcxYy1jYzVjLTQzNjYtYTNmMi0yNmEyYmI0ZDIyOTciLCJpYXQiOjE2ODA2NTYyODl9.l4crfrXdslwFVPOsuY-6ID5U1CLdgEu6Hwq2R7DRmwY

### Register a new user
POST {{url}}/users
Content-Type: application/json

{
    "name":"John Doe",
    "email":"john.doe@email.com",
    "password":"123456"
}

### Authenticate
POST {{url}}/sessions
Content-Type: application/json

{
    "email":"john.doe@email.com",
    "password":"123456"
}

### Get user profile
GET {{url}}/me
Content-Type: application/json
Authorization: {{token}}

### Create a gym
POST {{url}}/gyms
Content-Type: application/json
Authorization: {{token}}

{
    "title": "Gym Title",
    "description": "Gym Description",
    "phone": "99 9 9999-9999",
    "latitude": -22.8871799,
    "longitude": -46.9474326
}

### Create a check-in
POST {{url}}/gyms/afcdbc32-014b-4ac0-8afd-5df80b8b7f81/check-ins
Content-Type: application/json
Authorization: {{token}}

{
    "latitude": -22.8871799,
    "longitude": -46.9474326
}

### Create a check-in
GET {{url}}/check-ins/history
Content-Type: application/json
Authorization: {{token}}
